// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLoader: typeof import('./src/components/AppLoader.vue')['default']
    Badge: typeof import('./src/components/Badge.vue')['default']
    BoardCard: typeof import('./src/components/BoardCard.vue')['default']
    BoardColumnHeading: typeof import('./src/components/BoardColumnHeading.vue')['default']
    BoardComponent: typeof import('./src/components/BoardComponent.vue')['default']
    BoardHeading: typeof import('./src/components/BoardHeading.vue')['default']
    IssueColumn: typeof import('./src/components/IssueColumn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    TaskCreator: typeof import('./src/components/TaskCreator.vue')['default']
    TaskEditor: typeof import('./src/components/TaskEditor.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
  }
}

export {}
